//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use strum_macros::{Display, EnumString};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    Hash,
    EnumString,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "action")]
#[strum(serialize_all = "kebab_case", ascii_case_insensitive)]
pub enum Action {
    #[sea_orm(string_value = "view")]
    View,
    #[sea_orm(string_value = "edit")]
    Edit,
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "rename")]
    Rename,
    #[sea_orm(string_value = "assign")]
    Assign,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "alias_type")]
#[serde(rename_all = "kebab-case")]
pub enum AliasType {
    #[sea_orm(string_value = "site")]
    Site,
    #[sea_orm(string_value = "user")]
    User,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_revision_type")]
#[serde(rename_all = "kebab-case")]
pub enum FileRevisionType {
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "rollback")]
    Rollback,
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "undelete")]
    Undelete,
    #[sea_orm(string_value = "move")]
    Move,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "license")]
#[serde(rename_all = "kebab-case")]
pub enum License {
    #[sea_orm(string_value = "cc-by-sa-4.0")]
    #[serde(rename = "cc-by-sa-4.0")]
    CcBySa40,
    #[sea_orm(string_value = "cc-by-4.0")]
    #[serde(rename = "cc-by-4.0")]
    CcBy40,
    #[sea_orm(string_value = "cc-by-nd-4.0")]
    #[serde(rename = "cc-by-nd-4.0")]
    CcByNd40,
    #[sea_orm(string_value = "cc-by-nc-4.0")]
    #[serde(rename = "cc-by-nc-4.0")]
    CcByNc40,
    #[sea_orm(string_value = "cc-by-nc-sa-4.0")]
    #[serde(rename = "cc-by-nc-sa-4.0")]
    CcByNcSa40,
    #[sea_orm(string_value = "cc-by-nc-nd-4.0")]
    #[serde(rename = "cc-by-nc-nd-4.0")]
    CcByNcNd40,
    #[sea_orm(string_value = "cc-by-sa-3.0")]
    #[serde(rename = "cc-by-sa-3.0")]
    CcBySa30,
    #[sea_orm(string_value = "cc-by-3.0")]
    #[serde(rename = "cc-by-3.0")]
    CcBy30,
    #[sea_orm(string_value = "cc-by-nd-3.0")]
    #[serde(rename = "cc-by-nd-3.0")]
    CcByNd30,
    #[sea_orm(string_value = "cc-by-nc-3.0")]
    #[serde(rename = "cc-by-nc-3.0")]
    CcByNc30,
    #[sea_orm(string_value = "cc-by-nc-sa-3.0")]
    #[serde(rename = "cc-by-nc-sa-3.0")]
    CcByNcSa30,
    #[sea_orm(string_value = "cc-by-nc-nd-3.0")]
    #[serde(rename = "cc-by-nc-nd-3.0")]
    CcByNcNd30,
    #[sea_orm(string_value = "cc-by-sa-2.5")]
    #[serde(rename = "cc-by-sa-2.5")]
    CcBySa25,
    #[sea_orm(string_value = "cc-by-2.5")]
    #[serde(rename = "cc-by-2.5")]
    CcBy25,
    #[sea_orm(string_value = "cc-by-nd-2.5")]
    #[serde(rename = "cc-by-nd-2.5")]
    CcByNd25,
    #[sea_orm(string_value = "cc-by-nc-2.5")]
    #[serde(rename = "cc-by-nc-2.5")]
    CcByNc25,
    #[sea_orm(string_value = "cc-by-nc-sa-2.5")]
    #[serde(rename = "cc-by-nc-sa-2.5")]
    CcByNcSa25,
    #[sea_orm(string_value = "cc-by-nc-nd-2.5")]
    #[serde(rename = "cc-by-nc-nd-2.5")]
    CcByNcNd25,
    #[sea_orm(string_value = "gnu-fdl-1.3")]
    #[serde(rename = "gnu-fdl-1.3")]
    GnuFdl13,
    #[sea_orm(string_value = "gnu-fdl-1.2")]
    #[serde(rename = "gnu-fdl-1.2")]
    GnuFdl12,
    #[sea_orm(string_value = "gnu-fdl-1.1")]
    #[serde(rename = "gnu-fdl-1.1")]
    GnuFdl11,
    #[sea_orm(string_value = "cc0")]
    #[serde(rename = "cc0")]
    Cc0,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "message_recipient_type"
)]
#[serde(rename_all = "kebab-case")]
pub enum MessageRecipientType {
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "cc")]
    Cc,
    #[sea_orm(string_value = "bcc")]
    Bcc,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "page_revision_type")]
#[serde(rename_all = "kebab-case")]
pub enum PageRevisionType {
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "rollback")]
    Rollback,
    #[sea_orm(string_value = "undo")]
    Undo,
    #[sea_orm(string_value = "create")]
    Create,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "undelete")]
    Undelete,
    #[sea_orm(string_value = "move")]
    Move,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "relation_object_type"
)]
#[serde(rename_all = "kebab-case")]
pub enum RelationObjectType {
    #[sea_orm(string_value = "site")]
    Site,
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "page")]
    Page,
    #[sea_orm(string_value = "file")]
    File,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    Hash,
    EnumString,
    Display,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "resource")]
#[strum(serialize_all = "kebab_case", ascii_case_insensitive)]
pub enum Resource {
    #[sea_orm(string_value = "page")]
    Page,
    #[sea_orm(string_value = "role")]
    Role,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "text_block_type")]
#[serde(rename_all = "kebab-case")]
pub enum TextBlockType {
    #[sea_orm(string_value = "code")]
    Code,
    #[sea_orm(string_value = "html")]
    Html,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_type")]
#[serde(rename_all = "kebab-case")]
pub enum UserType {
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "site")]
    Site,
    #[sea_orm(string_value = "bot")]
    Bot,
}
